swagger: '2.0'
info:
  version: 'v1'
  title: 'EPI LandUse Permissibility'
  description: EPI LandUse Permissibility
  contact: {}
schemes: 
  - https
consumes:
- application/json
produces:
- application/json
host: 'api-uat.apps1.nsw.gov.au'
basePath: '/eplanning/data/v0/FetchEPILandUsePermissibility'
paths:
  '/FetchEPILandUsePermissibility/':
    get:
      description: This operation fetches land use permissibility based on the input parameters supplied.
      summary: FetchEPILandUsePermissibility
      operationId: FetchEPILandUsePermissibility
      deprecated: false
      produces:
      - application/json
      consumes:
      - application/json
      parameters:
      - name: EpiName
        in: header
        required: true
        type: string
        description: The Environmental Planning Instrument (EPI) for which the permissiblity details are requested.  
        
          The EPI name either fully or partially matches the legislative name as published on NSW Legislation website https://legislation.nsw.gov.au/browse/inforce.
          
          For example, to retrieve all the permissiblity details for Albury LEP, acceptable inputs are - 
          <UL>
          <li>
          Albury Local Environmental Plan 2010
          </li>
          <li>Albury </li>
          <li> Albury Local </li>  
          </UL>
      - name: ZoneCode
        in: header
        required: false
        type: string
        description:  This optional parameter allows to restrict the result set to a specific zone of interest. 
        
         If this parameter is not used, the permissibilty of all land uses under the EPI will be returned. 
         
         For example, supply \"R2\" to retrieve the pemissibliity of Low Density Residential.
      - name: ZoneDescription
        in: header
        required: false
        type: string
        description: This optional parameter allows to restrict the result set to a specific zone of interest. 
        
         If this parameter is not used, the permissibilty of all land uses under the EPI will be returned. 
         
         For example, supply \"Low Density Residential\" to retrieve the permissibility of R2. 
      responses:
        200:
          description:  An array of the following objects is returned. 
          headers: {}
          schema:
            $ref: '#/definitions/EPILandUsePermissibility'
        400:
          description: Client side exception
          schema:
            $ref: '#/definitions/clientSideErrorMessage'
   
definitions:
  EPILandUsePermissibility:
    type: array
    items:
      $ref: '#/definitions/EPILandUsePermissibilityList'
  EPILandUsePermissibilityList:
    type: object
    required:
      - EPIName
      - ZoneCode
      - ZoneDescription
      - ZoneObjective
      - Landuse
    properties:
      EPIName:
        type: string
        description: This field specifies the name of each environmental planning instrument supplied.
      Precinct:
        type: array
        items:
         $ref: '#/definitions/PrecinctList'
        description: This field returns the precinct name where it applies. For example  \"Sydney Harbour Catchment\" is one of the precincts retured for State Environmental Planning Policy (Biodiversity and Conservation) 2021.
  PrecinctList:
     type: object
     required:
      - Name
      - Zone
     properties:
      Name:
        type: string
        description: This field specifies the name of each environmental planning instrument supplied.
      Zone:
        type: array
        description: This field specifies the code of each land use zone under an EPI.
        items:
         $ref: '#/definitions/ZoneList'
  ZoneList:
    type: object
    required:
      - Name
      - Zone
    properties:
      ZoneCode:
        type: string
        description: This field specifies the code of each land use zone under an EPI.
      ZoneDescription:
        type: string
        description: This field specifies the description of each land use zone under an EPI.
      ZoneObjective: 
        type: string
        description: This field specifies the objectives for development for each zone.   
      Landuse:
        type: array
        items:
         $ref: '#/definitions/LanduseList'
  LanduseList:
        type: object
        properties:
             PermittedWithoutConsent:
              type: array
              items:
                $ref: '#/definitions/PermittedWithoutConsentList'
             PermittedWithConsent:
              type: array
              items:
                $ref: '#/definitions/PermittedWithConsentList'
             Prohibited:
              type: array
              items:
                $ref: '#/definitions/ProhibitedList'
  PermittedWithoutConsentList:
        type: object
        properties:
             Landuse:
              type: string
              description: This field specifies development that may be carried out without development consent for each zone.
  PermittedWithConsentList:
        type: object
        properties:
             Landuse:
              type: string
              description: This field specifies development that may be carried out only with development consent for each zone
             
  ProhibitedList:
        type: object
        properties:
             Landuse:
              type: string
              description: This field specifies development that is prohibited.
              
  clientSideErrorMessage:
      type: object
      properties:
        ErrorMessage:
          type: string
          description: 1. If EPI Name is not provided,"EPI Name cannot be empty" is returned. 2. If EPI Name is provided but a match is not found,"EPI Name cannot be found" is returned. 3. If Zone Code is provided but a match is not found,"Zone Code cannot be found" is returned. 4. If Zone Description is provided but a match is not found,"Zone Description cannot be found" is returned. 5. If both Zone Code and Zone Description are provided but a match is not found,"Could not find a record matching the Zone Code and Description" is returned. 6. If no records found matching the input parameters,"No results found" is returned.
          example: Refer to description for values
          
      
 